# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r1G2mbB6tyx3LtY94zueP6_QEimksKln
"""

n=int(input("Enter no. of participants "))
participants=[input() for i in range(n)]
print(participants)
import random
m=random.randint(0,n-1)
participants[m]